// ⚠️ PRECIOS ESTIMADOS — no proceden de la carta real (no existe lista de precios pública).
// Los NOMBRES de los platos sí están verificados: extraídos de reseñas reales en Tripadvisor
// y Restaurant Guru. Revisar y corregir precios antes de publicar.

const MENU_CATEGORIES = [
  { id: "desayunos", label: { es: "Desayunos", en: "Breakfast" } },
  { id: "entrantes", label: { es: "Entrantes", en: "Starters" } },
  { id: "mar", label: { es: "Del Mar", en: "From the Sea" } },
  { id: "italiano", label: { es: "Italiano", en: "Italian" } },
  { id: "postres", label: { es: "Postres", en: "Desserts" } },
  { id: "bebidas", label: { es: "Bebidas", en: "Drinks" } },
];

const MENU_ITEMS = [
  {
    id: "tostada-aguacate",
    category: "desayunos",
    nombre: { es: "Tostada de aguacate", en: "Avocado toast" },
    desc: {
      es: "Pan artesanal, aguacate fresco, tomate cherry y un toque de lima.",
      en: "Artisan bread, fresh avocado, cherry tomato and a touch of lime.",
    },
    precio: 12,
    img: "img/platos/desayuno.jpg",
    tags: ["vegano"],
  },
  {
    id: "smoothie-bowl",
    category: "desayunos",
    nombre: { es: "Smoothie bowl tropical", en: "Tropical smoothie bowl" },
    desc: {
      es: "Frutas de temporada, granola casera y miel de abeja local.",
      en: "Seasonal fruit, house-made granola and local honey.",
    },
    precio: 11,
    img: "img/platos/frutas-frescas.jpg",
    tags: ["vegano"],
  },
  {
    id: "panqueques",
    category: "desayunos",
    nombre: { es: "Panqueques de la casa", en: "House pancakes" },
    desc: {
      es: "Con sirope de maple, frutos rojos y mantequilla batida.",
      en: "With maple syrup, berries and whipped butter.",
    },
    precio: 10,
    img: "img/platos/desayuno.jpg",
    tags: [],
  },
  {
    id: "coctel-camarones",
    category: "entrantes",
    nombre: { es: "Cóctel de camarones", en: "Shrimp cocktail" },
    desc: {
      es: "Camarones frescos del Caribe en salsa cóctel de la casa.",
      en: "Fresh Caribbean shrimp in house cocktail sauce.",
    },
    precio: 16,
    img: "img/platos/coctel-camarones.jpg",
    tags: ["estrella"],
  },
  {
    id: "calamares",
    category: "entrantes",
    nombre: { es: "Calamares fritos", en: "Fried calamari" },
    desc: {
      es: "Ligeramente empanizados y fritos al punto, con alioli.",
      en: "Lightly battered and fried to perfection, served with aioli.",
    },
    precio: 14,
    img: "img/platos/plato-brocoli.jpg",
    tags: [],
  },
  {
    id: "sopa-mariscos",
    category: "entrantes",
    nombre: { es: "Sopa de mariscos", en: "Seafood soup" },
    desc: {
      es: "Caldo de pescado y mariscos con vegetales frescos.",
      en: "Fish and shellfish broth with fresh vegetables.",
    },
    precio: 13,
    img: "img/platos/sopa.jpg",
    tags: [],
  },
  {
    id: "bowl-vegano",
    category: "entrantes",
    nombre: { es: "Bowl vegano", en: "Vegan bowl" },
    desc: {
      es: "Generosa porción de vegetales de temporada, granos y aderezo cítrico.",
      en: "A generous portion of seasonal vegetables, grains and citrus dressing.",
    },
    precio: 14,
    img: "img/platos/frutas-frescas.jpg",
    tags: ["vegano", "estrella"],
  },
  {
    id: "dorado-maracuya",
    category: "mar",
    nombre: { es: "Dorado con salsa de maracuyá", en: "Mahi-mahi with passion fruit sauce" },
    desc: {
      es: "Dorado fresco a la plancha bañado en salsa de maracuyá de la casa.",
      en: "Fresh grilled mahi-mahi with house passion fruit sauce.",
    },
    precio: 24,
    img: "img/platos/steak.jpg",
    tags: ["estrella"],
  },
  {
    id: "pescado-frito",
    category: "mar",
    nombre: { es: "Pescado frito entero", en: "Whole fried fish" },
    desc: {
      es: "Favorito local: sabor delicado y textura crujiente.",
      en: "A local favorite: delicate flavor and crispy texture.",
    },
    precio: 22,
    img: "img/platos/coctel-camarones.jpg",
    tags: ["estrella"],
  },
  {
    id: "gratinado-mariscos",
    category: "mar",
    nombre: { es: "Gratinado de mariscos", en: "Seafood gratin" },
    desc: {
      es: "Mariscos frescos gratinados con queso y hierbas.",
      en: "Fresh shellfish gratin with cheese and herbs.",
    },
    precio: 26,
    img: "img/platos/sopa.jpg",
    tags: [],
  },
  {
    id: "langostinos-ajillo",
    category: "mar",
    nombre: { es: "Langostinos al ajillo", en: "Garlic butter prawns" },
    desc: {
      es: "Langostinos salteados en mantequilla, ajo y perejil fresco.",
      en: "Prawns sautéed in butter, garlic and fresh parsley.",
    },
    precio: 23,
    img: "img/platos/steak.jpg",
    tags: [],
  },
  {
    id: "pasta-mariscos",
    category: "italiano",
    nombre: { es: "Pasta ai frutti di mare", en: "Seafood pasta" },
    desc: {
      es: "Pasta artesanal con mariscos del día en salsa de tomate.",
      en: "House-made pasta with the day's shellfish in tomato sauce.",
    },
    precio: 20,
    img: "img/platos/pasta-italiana.jpg",
    tags: [],
  },
  {
    id: "pizza-lena",
    category: "italiano",
    nombre: { es: "Pizza al horno de leña", en: "Wood-fired pizza" },
    desc: {
      es: "Masa madre fermentada 48 horas, horneada al horno de leña.",
      en: "48-hour fermented sourdough, baked in our wood-fired oven.",
    },
    precio: 17,
    img: "img/platos/plato-brocoli.jpg",
    tags: [],
  },
  {
    id: "hamburguesa-enjoy",
    category: "italiano",
    nombre: { es: "Hamburguesa Enjoy", en: "Enjoy burger" },
    desc: {
      es: "Carne premium, queso fundido y papas de la casa.",
      en: "Premium beef, melted cheese and house-cut fries.",
    },
    precio: 15,
    img: "img/ambiente/ambiente-mesa.jpg",
    tags: [],
  },
  {
    id: "cheesecake",
    category: "postres",
    nombre: { es: "Cheesecake de la casa", en: "House cheesecake" },
    desc: {
      es: "Cremoso, con coulis de frutos rojos.",
      en: "Creamy, with a berry coulis.",
    },
    precio: 9,
    img: "img/platos/cheesecake.jpg",
    tags: ["estrella"],
  },
  {
    id: "gelato",
    category: "postres",
    nombre: { es: "Gelato artesanal", en: "Artisan gelato" },
    desc: {
      es: "Sabores rotativos, hecho en casa a diario.",
      en: "Rotating flavors, made fresh daily in-house.",
    },
    precio: 7,
    img: "img/platos/postre-chocolate.jpg",
    tags: ["vegano"],
  },
  {
    id: "pastel-chocolate",
    category: "postres",
    nombre: { es: "Pastel de chocolate", en: "Chocolate cake" },
    desc: {
      es: "Bizcocho húmedo de chocolate con ganache.",
      en: "Moist chocolate sponge with ganache.",
    },
    precio: 9,
    img: "img/platos/pastel.jpg",
    tags: [],
  },
  {
    id: "cafe-borbone",
    category: "bebidas",
    nombre: { es: "Café Borbone", en: "Borbone coffee" },
    desc: {
      es: "Café italiano de especialidad, tostado en Borbone.",
      en: "Specialty Italian coffee, roasted by Borbone.",
    },
    precio: 4,
    img: "img/platos/cafe-borbone.jpg",
    tags: [],
  },
  {
    id: "sangria",
    category: "bebidas",
    nombre: { es: "Sangría de la casa", en: "House sangria" },
    desc: {
      es: "Vino tinto, frutas frescas y un toque de brandy.",
      en: "Red wine, fresh fruit and a splash of brandy.",
    },
    precio: 8,
    img: "img/platos/sangria.jpg",
    tags: [],
  },
  {
    id: "mamajuana",
    category: "bebidas",
    nombre: { es: "Mamajuana", en: "Mamajuana" },
    desc: {
      es: "El clásico trago dominicano de raíces y ron macerado.",
      en: "The classic Dominican root-and-rum infused drink.",
    },
    precio: 9,
    img: "img/platos/mamajuana.jpg",
    tags: ["estrella"],
  },
  {
    id: "coctel-tropical",
    category: "bebidas",
    nombre: { es: "Cóctel tropical de la casa", en: "House tropical cocktail" },
    desc: {
      es: "Ron dominicano, maracuyá y menta fresca.",
      en: "Dominican rum, passion fruit and fresh mint.",
    },
    precio: 10,
    img: "img/platos/coctel-verde.jpg",
    tags: [],
  },
];
