tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#4a463f",
        error: "#ba1a1a",
        "on-secondary-fixed": "#001c37",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#7d2d00",
        "surface-dim": "#dcd9d9",
        "primary-container": "#c0541e",
        "on-secondary": "#ffffff",
        "outline-variant": "#dec0b5",
        "primary-fixed-dim": "#ffb597",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#abc9f1",
        "on-surface-variant": "#57423a",
        "surface-bright": "#fcf9f8",
        surface: "#fcf9f8",
        "surface-tint": "#a23f06",
        "tertiary-fixed-dim": "#ccc6bc",
        "tertiary-fixed": "#e8e2d8",
        "surface-container-highest": "#e5e2e1",
        secondary: "#436083",
        "on-primary": "#ffffff",
        "on-background": "#1c1b1b",
        "surface-container": "#f0eded",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#2b486a",
        "inverse-surface": "#313030",
        "surface-container-low": "#f6f3f2",
        "on-secondary-container": "#405d80",
        "primary-fixed": "#ffdbcd",
        "secondary-fixed": "#d2e4ff",
        "on-primary-fixed": "#360f00",
        "on-tertiary-fixed": "#1e1b15",
        "on-tertiary": "#ffffff",
        "surface-variant": "#e5e2e1",
        "on-tertiary-container": "#fffbff",
        "inverse-primary": "#ffb597",
        "on-primary-container": "#fffbff",
        background: "#fcf9f8",
        "inverse-on-surface": "#f3f0ef",
        "tertiary-container": "#78746c",
        tertiary: "#5f5b54",
        "on-surface": "#1c1b1b",
        primary: "#9f3d04",
        "surface-container-high": "#eae7e7",
        "secondary-container": "#b9d7ff",
        outline: "#8a7268",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "section-gap": "80px",
        base: "8px",
        "margin-mobile": "16px",
        "container-max": "1200px",
        gutter: "24px",
      },
      fontFamily: {
        "headline-sm": ["Playfair Display"],
        "display-lg-mobile": ["Playfair Display"],
        "body-lg": ["Hanken Grotesk"],
        "label-caps": ["Hanken Grotesk"],
        "display-lg": ["Playfair Display"],
        "body-md": ["Hanken Grotesk"],
        "headline-md": ["Playfair Display"],
      },
      fontSize: {
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg-mobile": ["40px", { lineHeight: "48px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" }],
        "display-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
      },
    },
  },
};
